@startuml
skinparam classAttributeIconSize 0

class 図書 {
  - 管理番号
  - 種別（書籍/雑誌）
}

class 学生証
class 職員証
class 利用者 {
  - 会員番号（学籍番号/職員番号）
}
class 学生
class 教職員
class 貸出履歴 {
  - 貸出日
  - 返却日
}
class 予約カード
class メール

利用者 "1" -- "1" 学生証
利用者 "1" -- "1" 職員証
利用者 <|-- 学生
利用者 <|-- 教職員

利用者 "1" -- "*" 貸出履歴 : 借りる/返す
図書 "1" -- "*" 貸出履歴 : 記録

利用者 "1" -- "*" 予約カード : 予約する
図書 "1" -- "*" 予約カード : 対象

利用者 "1" -- "*" メール : 通知する

@enduml