@startuml メニュー項目
left to right direction
actor "事務職員" as ac1
rectangle  大原情報科学大学・図書館システム as system {
  usecase "貸し出し予約" as UC1
  usecase "貸し出し・返却" as UC2
  usecase "記録・閲覧" as UC3
  usecase "メール送信" as UC4
  
}
UC2 --> UC1
UC2 --> UC4
ac1 -- UC3
ac1 -- UC2



@enduml