@startuml Robodogクラス図
skinparam classAttributeIconSize 0
hide circle

class RoboDog {
 -myName: String
 -myTime: int
 -goodMorning: String
 -goodAfternoon: String
 -goodNight: String
 -firstValue: int
 -secondValue: int
'  -教科書にはない
 -result: int

 +getMyName(): String
 +setMyName(): int
 +setNewTime(): void
 +getMyGreeting(): String
'-教科書にはない
 +setTwoValues(): void
 +setAndGetResult(): int
}

@enduml
